# Generated by Django 2.2.26 on 2023-05-25 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ppm', '0001_initial'),
        ('crm', '0002_auto_20230525_1734'),
        ('doc', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrelated',
            name='DocRelated_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CT_namedr', to='ppm.ContractMaster', verbose_name='相关合同'),
        ),
        migrations.AddField(
            model_name='documentrelated',
            name='DocRelated_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cust_namedr', to='crm.CustomerMaster', verbose_name='相关客户'),
        ),
        migrations.AddField(
            model_name='documentrelated',
            name='DocRelated_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opp_namedr', to='crm.OpportunityMaster', verbose_name='相关商机'),
        ),
        migrations.AddField(
            model_name='documentrelated',
            name='DocRelated_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Prj_namedr', to='ppm.ProjectMaster', verbose_name='相关项目'),
        ),
        migrations.AddField(
            model_name='documentrelated',
            name='DocRelated_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Act_namedr', to='workflow.RequestMaster', verbose_name='相关活动'),
        ),
    ]
