# Generated by Django 2.2.26 on 2023-05-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_auto_20230525_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmaster',
            name='on_webpage',
            field=models.BooleanField(default=False, verbose_name='网页展示'),
        ),
        migrations.AddField(
            model_name='resourcemaster',
            name='on_webpage',
            field=models.BooleanField(default=False, verbose_name='网页展示'),
        ),
    ]
