# Generated by Django 2.2.26 on 2023-05-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='psm_funnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '商机漏斗',
                'verbose_name_plural': '商机漏斗',
            },
        ),
        migrations.CreateModel(
            name='psm_myself',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '我的日程',
                'verbose_name_plural': '我的日程',
            },
        ),
    ]
