# Generated by Django 2.2.26 on 2023-05-25 09:34

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMaster',
            fields=[
                ('Data_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_code', models.CharField(max_length=10, verbose_name='联系人代码')),
                ('Contact_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人名称')),
                ('Contact_source', models.CharField(blank=True, choices=[('CAMP', '营销活动'), ('AGENT', '代理推荐'), ('SELF', '自己发掘')], max_length=60, null=True, verbose_name='来源')),
                ('Contact_method', models.CharField(blank=True, choices=[('EMAIL', '电子邮件'), ('CALL', '电话'), ('WECHAT', '微信')], max_length=12, null=True, verbose_name='联系方式')),
                ('Contact_content', models.TextField(blank=True, max_length=40, null=True, verbose_name='联系内容')),
                ('Contact_card', models.ImageField(blank=True, null=True, upload_to='', verbose_name='名片')),
                ('Contact_scanflag', models.CharField(blank=True, choices=[('99', '手工输入'), ('00', '待识别'), ('01', '已识别')], default='99', max_length=16, null=True, verbose_name='识别标识')),
                ('Data_security', models.CharField(choices=[('10', '10'), ('30', '30'), ('50', '50'), ('100', '100')], max_length=10, verbose_name='权限级别')),
                ('Contact_status', models.CharField(choices=[('OPEN', '待办'), ('APPROVED', '已批准'), ('STOPPED', '停止')], default='OPEN', max_length=10, validators=[django.core.validators.MinLengthValidator(1, message='20警示：')], verbose_name='状态')),
                ('Contact_date', models.DateField(blank=True, null=True, verbose_name='日期')),
                ('Data_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='日期')),
                ('Dummy_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='流水号')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
            },
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('Data_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_code', models.CharField(max_length=10, verbose_name='客户代码')),
                ('Customer_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='客户名称')),
                ('Customer_address', models.TextField(blank=True, max_length=200, null=True, verbose_name='客户地址')),
                ('Customer_type', models.CharField(choices=[('SUSPECT', 'Suspect潜在'), ('LEADS', 'Leads线索'), ('PROSPECT', 'Prospect意向'), ('CUSTOMER', 'Customer客户')], max_length=20, null=True, verbose_name='类型')),
                ('Customer_source', models.CharField(blank=True, choices=[('CAMP', '营销活动'), ('AGENT', '代理推荐'), ('SELF', '自己发掘')], max_length=60, null=True, verbose_name='来源')),
                ('Data_security', models.CharField(choices=[('10', '10'), ('30', '30'), ('50', '50'), ('100', '100')], max_length=10, verbose_name='权限级别')),
                ('Customer_status', models.CharField(choices=[('OPEN', '待办'), ('APPROVED', '已批准'), ('STOPPED', '停止')], default='OPEN', max_length=10, validators=[django.core.validators.MinLengthValidator(1, message='20警示：')], verbose_name='状态')),
                ('Data_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='日期')),
                ('Dummy_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='流水号')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='OpportunityMaster',
            fields=[
                ('Data_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Opportunity_code', models.CharField(max_length=20, null=True, verbose_name='商机代码')),
                ('Opportunity_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='商机名称')),
                ('Opportunity_source', models.CharField(choices=[('CAMP', '营销活动'), ('AGENT', '代理推荐'), ('SELF', '自己发掘')], max_length=10, null=True, verbose_name='来源')),
                ('Opportunity_initialamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='原始标的')),
                ('Opportunity_currentamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='当前标的')),
                ('Opportunity_finalamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='最终标的')),
                ('Opportunity_nowstage', models.CharField(blank=True, max_length=20, null=True, verbose_name='当前进展')),
                ('Opportunity_nextstage', models.CharField(blank=True, max_length=20, null=True, verbose_name='接续目标')),
                ('Data_security', models.CharField(choices=[('10', '10'), ('30', '30'), ('50', '50'), ('100', '100')], max_length=10, verbose_name='权限级别')),
                ('Opportunity_ownershare', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='分担份额%')),
                ('Opportunity_secondshare', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='分担份额%')),
                ('Opportunity_status', models.CharField(choices=[('OPEN', '待办'), ('APPROVED', '已批准'), ('STOPPED', '停止')], default='OPEN', max_length=10, validators=[django.core.validators.MinLengthValidator(1, message='20警示：')], verbose_name='状态')),
                ('Opportunity_date', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='商机日期')),
                ('Opportunity_comments', models.TextField(blank=True, max_length=800, null=True, verbose_name='备注')),
                ('Data_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Data日期')),
                ('Dummy_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='流水号')),
                ('Data_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opp_userda', to=settings.AUTH_USER_MODEL, verbose_name='审批者')),
                ('Data_bu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Data_buo0', to='base.BUMaster', to_field='BU_code', verbose_name='所属BU')),
                ('Data_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opp_userdc', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('Data_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opp_userdo', to=settings.AUTH_USER_MODEL, verbose_name='拥有者')),
                ('Data_secondowner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opp_userds', to=settings.AUTH_USER_MODEL, verbose_name='第二拥有者')),
                ('Opportunity_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opp_cont', to='crm.ContactMaster', verbose_name='联系人')),
                ('Opportunity_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opp_cust', to='crm.CustomerMaster', verbose_name='客户')),
            ],
            options={
                'verbose_name': '商机',
                'verbose_name_plural': '商机',
                'ordering': ['Data_bu', 'Opportunity_code'],
            },
        ),
    ]
