# Generated by Django 2.2.26 on 2023-05-25 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20230525_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunitymaster',
            name='Opportunity_flowcycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opp_salscycle1', to='workflow.FlowType', verbose_name='销售周期'),
        ),
        migrations.AddField(
            model_name='opportunitymaster',
            name='Opportunity_serviceitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Opp_item', to='base.ItemMaster', verbose_name='服务内容'),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='Customer_contact1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cust_cont1', to='crm.ContactMaster', verbose_name='联系人1'),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='Customer_contact2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cust_cont2', to='crm.ContactMaster', verbose_name='联系人2'),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='Customer_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ind_name', to='base.BuParameter', verbose_name='行业'),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='Customer_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Scal_name', to='base.BuParameter', verbose_name='规模'),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='Customer_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Type_name', to='base.BuParameter', verbose_name='服务类型'),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='Data_bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Data_buc0', to='base.BUMaster', to_field='BU_code', verbose_name='所属BU'),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='Data_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cust_userdc', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='Data_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cust_userdo', to=settings.AUTH_USER_MODEL, verbose_name='拥有者'),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='Data_secondowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cust_userds', to=settings.AUTH_USER_MODEL, verbose_name='第二拥有者'),
        ),
        migrations.AddField(
            model_name='contactmaster',
            name='Data_bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Data_buc1', to='base.BUMaster', to_field='BU_code', verbose_name='所属BU'),
        ),
        migrations.AddField(
            model_name='contactmaster',
            name='Data_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_namecc1', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='contactmaster',
            name='Data_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_nameco1', to=settings.AUTH_USER_MODEL, verbose_name='拥有者'),
        ),
        migrations.CreateModel(
            name='OpportunityApprove',
            fields=[
            ],
            options={
                'verbose_name': '商机批准',
                'verbose_name_plural': '商机批准',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('crm.opportunitymaster',),
        ),
        migrations.AlterUniqueTogether(
            name='opportunitymaster',
            unique_together={('Data_bu', 'Opportunity_code')},
        ),
    ]
