# Generated by Django 2.2.26 on 2023-05-26 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20230525_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='User_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_interest', to='doc.ResourceMaster', verbose_name='关注对象'),
        ),
        migrations.AlterField(
            model_name='userthumbup',
            name='User_thumbup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_thumbup', to='doc.ResourceMaster', verbose_name='资源点赞'),
        ),
    ]
