# Generated by Django 2.2.26 on 2023-05-26 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230526_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='User_myself',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_myself', to=settings.AUTH_USER_MODEL, verbose_name='关注人'),
        ),
        migrations.AlterField(
            model_name='userthumbup',
            name='Job_thumbup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Job_thumbup', to='doc.JobMaster', verbose_name='Job点赞'),
        ),
        migrations.AlterField(
            model_name='userthumbup',
            name='User_myself',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_myself0', to=settings.AUTH_USER_MODEL, verbose_name='关注人'),
        ),
    ]
