# Generated by Django 2.2.26 on 2023-05-25 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doc', '0002_auto_20230525_1734'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppm', '0001_initial'),
        ('base', '0002_auto_20230525_1734'),
        ('crm', '0002_auto_20230525_1734'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaster',
            name='Project_flowcycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Prj_cycle', to='workflow.FlowType', verbose_name='项目周期'),
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='Project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cont_acct1', to=settings.AUTH_USER_MODEL, verbose_name='项目经理'),
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='Project_opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prj_oppo1', to='crm.OpportunityMaster', verbose_name='来自商机'),
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='Project_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prj_prj1', to='ppm.ProjectMaster', verbose_name='上级项目'),
        ),
        migrations.AddField(
            model_name='projectmaster',
            name='Project_serviceitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Pro_itemsi', to='base.ItemMaster', verbose_name='服务内容'),
        ),
        migrations.AddField(
            model_name='contractresourcemaster',
            name='Contract_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cont_code0', to='ppm.ContractMaster', verbose_name='合同代码'),
        ),
        migrations.AddField(
            model_name='contractresourcemaster',
            name='Data_bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Data_bucctr', to='base.BUMaster', to_field='BU_code', verbose_name='所属BU'),
        ),
        migrations.AddField(
            model_name='contractmaster',
            name='Contract_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ct_cust1', to='crm.CustomerMaster', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='contractmaster',
            name='Contract_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ct_doc1', to='doc.DocumentMaster', verbose_name='相关文档'),
        ),
        migrations.AddField(
            model_name='contractmaster',
            name='Contract_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ct_acct1', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='contractmaster',
            name='Data_bu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Data_bucctm', to='base.BUMaster', to_field='BU_code', verbose_name='所属BU'),
        ),
        migrations.AddField(
            model_name='contractmaster',
            name='Data_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ct_userdc', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='contractmaster',
            name='Data_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ct_userdq', to=settings.AUTH_USER_MODEL, verbose_name='拥有者'),
        ),
        migrations.AddField(
            model_name='contractmaster',
            name='Data_secondowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ct_userds', to=settings.AUTH_USER_MODEL, verbose_name='第二拥有者'),
        ),
        migrations.CreateModel(
            name='ProjectApprove',
            fields=[
            ],
            options={
                'verbose_name': '项目批准',
                'verbose_name_plural': '项目批准',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ppm.projectmaster',),
        ),
        migrations.CreateModel(
            name='ProjectResourceAssign',
            fields=[
            ],
            options={
                'verbose_name': '项目资源安排',
                'verbose_name_plural': '项目资源安排',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ppm.projectmaster',),
        ),
    ]
